[build]
base = "."
command = "yarn build"
publish = "./build/"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[build.environment]
REACT_APP_API_URL = "https://api-pensamdoemmim.onrender.com"
